spring:
    jpa:
        show-sql: true
        database: mysql
        hibernate:
            ddl-auto: update

    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/Job_P2P
        username: root
        password: mysql